### ISSUE TITLE
Shortcut Automation Not Working ?

### ISSUE THREAD

**Issue by maximnine** [GenjiApp/RingerVolume#26]
iPhone 13 Pro
iOS 16.3.1
No Jailbreak
=======
I managed to Build and Install using Xcode
The application can run perfectly
I can adjust Ringer Volume with Slider
But, Shortcut is not working

When running Set Ringer Volume,
It just opened the App.
Ringer Volume does not change.
What did I miss?

**Comment by GenjiApp** [comment]
In my environment, iPhone 8 & iOS 16.3.1, the shortcut action works correctly.
I don't know why it doesn't work in your environment.

Try to build a shortcut that have only one action "Set Ringer Volume". Does it work or not work?

**Comment by maximnine** [comment]
**_Try to build a shortcut that have only one action "Set Ringer Volume". Does it work or not work?_**

No, It still doesnt work.
Maybe if You (or your friend) have spare iPhone 13, You can try to test it ?

To be honest,
This application is very important.
Don't know why Apple didn't add this as a standard feature.

**Comment by GenjiApp** [comment]
No, I can't test other than iPhone 8.

**Comment by maximnine** [comment]
It is deeply regretted.
Hopefully in the future you can improve this application.
Thanks for the effort. :)

**Comment by batuhan0sanli** [comment]
I am also having this problem on iPhone 13 pro :(
I would like to review the codes and do some experimentation.

**Comment by maximnine** [comment]
> I am also having this problem on iPhone 13 pro :( I would like to review the codes and do some experimentation.

That's great
Hope you find a solution for this soon

**Comment by batuhan0sanli** [comment]
> > I am also having this problem on iPhone 13 pro :( I would like to review the codes and do some experimentation.
> 
> That's great Hope you find a solution for this soon

I'm encountering a very interesting situation. I download the project and update the AppIDs. Then, when I install the app directly on my phone with Xcode, the shortcuts work perfectly. However, since I don't have an Apple developer account, I can't open the application after 3 days. I found ways to convert the `xcodeproj` file to an `ipa` file and installed it using Altstore with sideloading, and the application works, but I'm experiencing this problem with shortcuts. It's very intriguing.

**Comment by GenjiApp** [comment]
On another note, I happen to own an iPad mini 6, which was released in the same year as iPhone 13 Pro. Just like the iPhone 13 Pro, this device does not have a home button.

I tested the RingerVolume app on iPad mini 6, and the shortcut action worked perfectly.

I have no idea why the shortcut action doesn't work properly on iPhone 13 Pro.

And, I take no account of AltStore/Sideloading.

**Comment by maximnine** [comment]
Without UnInstalling previous Installation.
I managed to Update to iOS 17.1
And somehow, It worked.
😁😁😁

The App and when I make Shortcut and Automation, it worked too.

**Comment by GenjiApp** [comment]
Sounds good!

**Comment by niXta1** [comment]
> Without UnInstalling previous Installation.
> I managed to Update to iOS 17.1
> And somehow, It worked.
> 😁😁😁
> 
> The App and when I make Shortcut and Automation, it worked too.

Changing the ringer volume is supported out of the box with ios 17.

**Comment by GenjiApp** [comment]
Thank you for the report.
