### ISSUE TITLE
.ipa compilation

### ISSUE THREAD

**Issue by verone0001** [GenjiApp/RingerVolume#28]
Hello,

I know there is no possibility to publish the app in the AppStore, but would there be any to build it and push the .ipa to the repo so we can sideload it ourselves with e.g. AltServer (they included [app sideload](https://faq.altstore.io/release-notes/altserver#direct-.ipa-sideloading) very recently)?

I don’t have a Mac to compile it myself nor could make it work by installing a VM to emulate it and compile it.

Thanks in advance.

**Comment by GenjiApp** [comment]
I don't know AltStore / sideloading. I'm not interest in them.

**Comment by verone0001** [comment]
Sure, but for us who sideload apps with them, can we have it compiled and pushed to the repo so we can download it directly?

I think it would be much easier and usable for more users!

Thanks.
